version: "3"
services:
  app:
    build: .
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    healthcheck:
      test: curl --fail http://localhost:3000/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  redis:
    image: redis:alpine
    healthcheck:
      test: redis-cli ping
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
